### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by karlkfi** [PiotrGrochowski/Consolas#1]
Tag says public-domain, but there's no license file or mention of license in the readme.

**Comment by oxguy3** [comment]
The metadata of the .sfd files says "(c) 2018 Microsoft Corporation. All rights reserved." I'm pretty sure that PiotrGrochowski has no affiliation with or permission from Microsoft, and the font has not actually been made FOSS.

**Comment by cup** [comment]
https://github.com/PiotrGrochowski/Consolas/issues/2

**Comment by cup** [comment]
Please dont install this software - see the linked issue

in addition i have reported @PiotrGrochowski for copyright violation and for malware.

**Comment by cup** [comment]
https://github.com/MicrosoftDocs/typography-issues/issues/173
https://github.com/PiotrGrochowski/Consolas/issues/1
https://github.com/PiotrGrochowski/Consolas/issues/2

**Comment by PiotrGrochowski** [comment]
> 
> 
> Tag says public-domain, but there's no license file or mention of license in the readme.

If there was a licence, this would be proprietary and copyrighted. Obviously not a very good idea for a font that's to be widely seen. All small files (such as retro games or the Consolas font) are virtually public domain as they are redistributed quicker than they can be taken down. Therefore it's safer to make such files officially public domain. Also, ttf files are open source because they are the source.

**Comment by cup** [comment]
@PiotrGrochowski i dont think you understand how open source works.

just because you found the SFD files and illegally distributed them doesnt make this open source, it just makes you a criminal.

microsoft, the actual copyright owner, can corroborate what you are saying. otherwise this repository is nothing more than proof that you have violated the Digital Millennium Copyright Act, a federal crime in the united states.

**Comment by oxguy3** [comment]
The fact that the file is small does not make it public domain. Every creative work is copyrighted so long as it exceeds the [threshold of originality](https://en.wikipedia.org/wiki/Threshold_of_originality), which an entire font definitely does.

Perhaps you're thinking of the [de minimis](https://en.wikipedia.org/wiki/De_minimis) doctrine, which is the practice that using a very small portion of a copyrighted work in a much larger work is not considered infringement (e.g. if you took a photo of a crowd, and someone in the crowd had a copyrighted design on their t-shirt, your photo wouldn't be considered an infringing work). You've used the entire font and your new versions of the font use most of the original font, so de minimis would definitely not apply.

**Comment by PiotrGrochowski** [comment]
The thing is, small files like retro games or font files are redistributed quicker than they can ever be taken down!

**Comment by cup** [comment]
@PiotrGrochowski your logic is laughably flawed - for example:

> if you murder someone and no one sees you, its not a crime!

yes it is. just because you havent been brought to justice yet doesnt mean that
its legal. stop it.

**Comment by oxguy3** [comment]
Sure, and sometimes I drive 5 mph over the speed limit. Doesn't make it legal. The font is not "open source", at least not in the sense that people typically use that term (i.e. as shorthand for "free and open source software (FOSS)"). If you want to distribute your own version of the font then that's fine, and Microsoft will probably never care enough to do anything about if, but don't act like you have permission or the font has been made open source.

**Comment by karlkfi** [comment]
Per [Wikipedia](https://en.m.wikipedia.org/wiki/Copyright_infringement):

> Copyright infringement (colloquially referred to as piracy) is the use of works protected by copyright law without permission, infringing certain exclusive rights granted to the copyright holder, such as the right to reproduce, distribute, display or perform the protected work, or to make derivative works.

Unless you are the copyright holder (sole originator) of all files, or you’ve received explicit permission from all copyright holders, you’ve probably violated at least 2 of those exclusive rights by hosting the font yourself, and another by distributing a modified version. 

Having no license doesn’t mean it’s public domain. Being on everyone’s computer doesn’t make it public domain. The only thing that makes something public domain is having it be older than the length of copyright protection by law, which is life of original authors + 70* years (depending on type of content).

Everything else needs a license if you want to grant more permissions than granted by copyright law.

**Comment by PiotrGrochowski** [comment]
Let's just say this repository is in _informal_ English. You know, that one that everyone on Earth uses.

**Comment by Studio384** [comment]
What is this repository being "informal English" gonna do? Look, it's pretty clear: you just put Consolas through a converter, ripped its chars and are putting it on GitHub as if you hold the rights. Fun fact: you don't. Consolas isn't an open source font and putting it on GitHub without a license doesn't make it open source (heck, anything of which you can view the code that does not carry a license is not open source), not to mention that you just published ttf files, not actual source files. You clearly don't understand how this works.

**Comment by PiotrGrochowski** [comment]
TTF files ARE the source. Not to mention, I spent hard work adding missing characters with FontForge.
