### ISSUE TITLE
License dispute is not finished yet

### ISSUE THREAD

**Issue by DBX12** [PiotrGrochowski/Consolas#3]
The repo owner just abused their power and closed an important issue (#1) and discussion as "too heated". Let's reopen that discussion here. Maybe we should keep opening issues. As per owners opinion, it's ok as long as the ~files~ issues are ~redistributed~ opened quicker than they can be ~taken down~ closed.

**Comment by ctolkien** [comment]
Don't really see there is much to dispute. There is no license, so this is not OSS.

**Comment by Studio384** [comment]
Indeed, he just ripped a font, and calls it his own because he added some chars to it (which I'll assume are probably just ripped from another font). Even if there is a license for OSS, he still wouldn't have the rights to do this anyways.

**Comment by PiotrGrochowski** [comment]
The new characters are not ripped from another font. Pretty much the only font that contains those missing characters is Unifont, but that font is too pixelated to work well with hinting. The new characters are made in FontForge.
