### ISSUE TITLE
PiotrGrochowski is a weiner 

### ISSUE THREAD

**Issue by skef** [PiotrGrochowski/Consolas#5]
This is important.

**Comment by ctrlcctrlv** [comment]
Definitely agreed. If not a weiner, at least a troll. If not a troll, at least at times insanely entitled.

BTW:
>*from a Microsoft employee* WHY THE HECK IS IT OPEN SOURCE?!

>Open source is the future, whether you like it or not. Consolas is one of the things that became open source as a result of future.

[source](https://github.com/PiotrGrochowski/Consolas/blob/ad3436da9259608d7cf3866f709a4235332d7b90/README.md#from-a-microsoft-employee-why-the-heck-is-it-open-source)

This is a completely invalid rationale. You've essentially stolen Consolas, let's be clear. Microsoft did not open source it as far as I know and your README acknowledges that. I'm pretty sure this repository breaks Github's terms of service.

**Comment by PiotrGrochowski** [comment]
> a troll.

the t-word is never accepted
